### ISSUE TITLE
Love the app!

### ISSUE THREAD

**Issue by melissamcewen** [rosalynnashwood/sezia#1]
Hi just wanted to drop a line and say I love it! I am a sometimes dev and have curlsbot.com that checks ingredients for the "curly girl" method. It's quite the challenge. I might make a page of products that pass both curlsbot +sezia when I have time.

**Comment by rosalynnashwood** [comment]
@melissamcewen  
Thanks so much! Right back at you, Curlsbot is looks great. I never heard of Lorraine Massey but I'll have to check it out when I get the chance. Sezia has a big update on the way, so be on the lookout for some really exciting changes. :)
